{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
{{- $fullName := include "bitwarden.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-pv
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- with .Values.persistence.annotations  }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    # app: {{ template "bitwarden.name" . }}
    # chart: {{ template "bitwarden.chart" . }}
    # release: {{ .Release.Name }}
    # heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end -}}
{{- end -}}
{{- end -}}